app.controller('BlogController',fuction($scope,$location,BlogService,$routeParams){
	var id=$routeParams.id;
	$scope.blogPost=BlogService.getBlogPostById(id)
	.then(function(response){
		$scope.blogPost=response.data
	},function(response){
		console.log(response.status)
})
$scope.addBlogComment=function(){
		$scope.blogComment.blogPost=$scope.blogPost;
		BlogService.addBlogComment($scope.blogcomment)
	.then(function(response){
		console.log(response.status);
		$scope.showcomments=true
		$scope.blogComment.body=''
		/*$location.path("/getBlogDetail/"+$scope.blogPost.id)*/
	},function(response){
		console.log(response.status)
})
	}
	$scope.getBlogComments=function(blogPostId){
		$scope.showcomments=true;
		$scope.blogComments=BlogService.getBlogComments(blogPostId)
	.then(function(response){
		$scope.blogComments=response.data;
	},function(response){
		console.log(response.status);
})
	}
	
})